on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"

name: ğŸ§ª Run Tests
jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        config: [Release, Debug]
        type: [gcc, clang, msvc, clang-cl, apple-clang]

        include:
          - type: gcc
            os: ubuntu-latest
            container: archlinux:base-devel
            deps: pacman --noconfirm -Syu git cmake gcc ninja make

          - type: clang
            os: ubuntu-latest
            container: archlinux:base-devel
            deps: pacman --noconfirm -Syu git cmake clang ninja make

          - type: msvc
            os: windows-latest

          - type: clang-cl
            os: windows-latest
            cmake_args: -T ClangCL -A x64

          - type: apple-clang
            os: macos-15
            xcode: 16.3

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    name: ${{ matrix.type }}-${{ matrix.config }}

    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v4

      - name: ğŸ§° Dependencies
        run: ${{ matrix.deps }}

      - name: ğŸ Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.type == 'apple-clang' }}
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: ğŸ”§ Compile
        run: |
          cmake -B build -Dereignis_tests=ON ${{ matrix.cmake_args }}
          cmake --build build --config ${{ matrix.config }}

      - name: ğŸ”¬ Run Tests
        run: |
          ctest --test-dir build/tests -C ${{ matrix.config }} --verbose
